#!/usr/bin/env bash
REGISTRY='localhost'

[[ -z "${1}" ]] && echo -e "\nError: At least one argument (instance name OR list/-l) is required to run this command." && exit 1

INSTANCE="${1}"

case "$1" in
	list|-l) docker ps -a | grep bashword;;
	*) shift; docker exec -i "bashword-${INSTANCE}" bashword.sh ${@};;
esac
